name: Upload artifact
description: Upload artifact to Google Cloud Storage
inputs:
  name:
    description: Artifact name
    required: true
  path:
    description: Directory to package
    required: true
runs:
  using: composite
  steps:
    - run: |
        set -o pipefail
        CI_ARTIFACTS_RUN_NUMBER=${CI_ARTIFACTS_RUN_NUMBER:-${{ github.run_number }}}
        URL="gs://${{ env.CI_ARTIFACTS_BUCKET }}/$CI_ARTIFACTS_RUN_NUMBER/${{ inputs.name }}.tar.zst"
        echo "--> Will upload to $URL"
        if ! tar -C "${{ inputs.path }}" -cf - . | zstd -T0 | gsutil cp - "$URL"; then
          echo "--> Artifact upload failed; cleaning up"
          gsutil rm "$URL" || true
          exit 1
        fi
      shell: bash
